### ISSUE TITLE
Crumbs fails to render without published view

### ISSUE THREAD

**Issue by pionl** [vixen-tech/laravel-breadcrumbs#1]
If I do not publish views to my vendor folder the view will not render.

Fails on `Undefined variable $attributes`.

Probably there needs to be some tweak.

Latest Laravel + PHP 8.1

Thanks for the new upgrade, I've already was using your old version of this and was quite happy using it :)

**Comment by atorscho** [comment]
Hi!

I am glad this package is helpful to some people :) 

I will take a look at it this afternoon

**Comment by pionl** [comment]
Thank you! 🚀 Have a great weekend

**Comment by atorscho** [comment]
Thanks to you for informing me and have a great weekend as well :)
